user nginx;
worker_processes 1;
include /etc/nginx/modules-enabled-test/*.conf;
events {}
http {
  include /etc/nginx/conf-test/05_njs.conf;
  include /etc/nginx/sites-test/30_metrics.conf;
  include /etc/nginx/sites-test/50_njs_periodics.conf;
  server {
    listen 80;
    location = /test/h { return 200 "$noslice_host\n"; }
  }
}
